name: 'Setup.Npmrc'
description: 'Create and configure .npmrc file'

inputs:
  install_sfp:
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    - run: |
        set -x
        echo "Creating .npmrc"
        echo "always_auth=true" >> .npmrc
        npm install -g @salesforce/cli --omit=dev
        if [[ "${{inputs.install_sfp}}" == "true" ]]; then npm install -g flxbl-io/sfp --omit=dev; fi

      shell: bash
    - run: |
        echo "Running SFPowerkit"
        sfpowerkit --version
      shell: bash
